import 'package:malltiverse/models/product.dart';

List<Product> productData = [
  Product(
      name: 'Touch Screen Smart Watch',
      imageUrl: 'assets/watch.png',
      description: 'For Android & IOS',
      displayPrice: 'N 9,170',
      quantity: 0,
      rating: 3,
      category: 'Tech Gadget',
      currentPrice: 9170),
  Product(
      name: 'Itel Bluetooth Earphones',
      imageUrl: 'assets/earbuds.png',
      description: 'BUDS ACE Wireless Earphones',
      displayPrice: 'N 17,660',
      quantity: 0,
      rating: 5,
      category: 'Tech Gadget',
      currentPrice: 17660),
  Product(
      name: 'Joystick Game Controller',
      imageUrl: 'assets/controller.png',
      description: 'Wired UCOM USB Pad....',
      displayPrice: 'N 11,250',
      quantity: 0,
      rating: 5,
      category: 'Tech Gadget',
      currentPrice: 11250),
  Product(
      name: 'Apple IPhone 14 Pro',
      imageUrl: 'assets/phone.png',
      description: '6GB RAM + 128GB ROM',
      displayPrice: 'N 1,450,000',
      quantity: 0,
      rating: 5,
      category: 'Tech Gadget',
      currentPrice: 1450000),
  Product(
      name: 'HP ENVY 15 X360',
      imageUrl: 'assets/laptop.png',
      description: 'INTEL Core i7 16GB RAM 512... ',
      displayPrice: 'N 1,300,000',
      quantity: 0,
      rating: 5,
      category: 'Tech Gadget',
      currentPrice: 1300000),
  Product(
      name: 'Oriamo 2000mAH PowerBank',
      imageUrl: 'assets/powerbank.png',
      description: 'Wired UCOM USB Pad for PC....',
      displayPrice: 'N 19,990',
      quantity: 0,
      rating: 4,
      category: 'Tech Gadget',
      currentPrice: 19990),
  Product(
      name: 'Men’s Belt Leather',
      imageUrl: 'assets/belt.png',
      description: 'Buckle Brown Timeless Belt',
      displayPrice: 'N 17,500',
      quantity: 0,
      rating: 4,
      category: 'Men\'s Fashion',
      currentPrice: 17500),
  Product(
      name: 'Quality Plain Face Cap',
      imageUrl: 'assets/cap.png',
      description: 'Plain Black Face Cap',
      displayPrice: 'N 4,000',
      quantity: 0,
      rating: 5,
      category: 'Men\'s Fashion',
      currentPrice: 4000),
  Product(
      name: 'Men’s Formal Lace Up Shoes',
      imageUrl: 'assets/men_shoe.png',
      description: 'Italian Brogues Leather Sh..',
      displayPrice: 'N 21,000',
      quantity: 0,
      rating: 4,
      category: 'Men\'s Fashion',
      currentPrice: 21000),
  Product(
      name: 'Men’s Short Sleeve ',
      imageUrl: 'assets/men_top.png',
      description: 'Casual Shirt - Black & Brown',
      displayPrice: 'N 25,900',
      quantity: 0,
      rating: 5,
      category: 'Men\'s Fashion',
      currentPrice: 25900),
  Product(
      name: 'Men’s Three Piece Tuxedo',
      imageUrl: 'assets/tux.png',
      description: 'Elegant Wedding Suit - Te... ',
      displayPrice: 'N 65,990',
      quantity: 0,
      rating: 4,
      category: 'Men\'s Fashion',
      currentPrice: 65990),
  Product(
      name: 'DesubClassic Quality Agbada',
      imageUrl: 'assets/men_trad.png',
      description: 'Black Agbada with a Black .....',
      displayPrice: 'N 85,000',
      quantity: 0,
      rating: 4,
      category: 'Men\'s Fashion',
      currentPrice: 85000),
  Product(
      name: 'Ladies Leather Chic Bag',
      imageUrl: 'assets/bag.png',
      description: 'Office Trendy Handbag ...',
      displayPrice: 'N 20,950',
      quantity: 0,
      rating: 4,
      category: 'Women\'s Fashion',
      currentPrice: 20950),
  Product(
      name: 'Summer Tie Neck Long Dress',
      imageUrl: 'assets/dress.png',
      description: 'Purple free Floral Dress',
      displayPrice: 'N 10,000',
      quantity: 0,
      rating: 5,
      category: 'Women\'s Fashion',
      currentPrice: 10000),
  Product(
      name: 'Ladies Crystal Bracelet',
      imageUrl: 'assets/jewellry.png',
      description: 'Silver Diamond Flower Brace....',
      displayPrice: 'N 3,234',
      quantity: 0,
      rating: 4,
      category: 'Women\'s Fashion',
      currentPrice: 3234),
  Product(
      name: 'Scarlet Darkness Dress',
      imageUrl: 'assets/my_dress.png',
      description: 'Summer Square Neck Sleeve..',
      displayPrice: 'N 10,500',
      quantity: 0,
      rating: 4,
      category: 'Women\'s Fashion',
      currentPrice: 10500),
  Product(
      name: 'Brown Crop Top Sweat Shirt',
      imageUrl: 'assets/women_top.png',
      description: 'Denami Women Diamond .....',
      displayPrice: 'N 9,500',
      quantity: 0,
      rating: 4,
      category: 'Women\'s Fashion',
      currentPrice: 9500),
  Product(
      name: 'Corporate High Heel',
      imageUrl: 'assets/women_shoe.png',
      description: 'Leather cover shoe - Black',
      displayPrice: 'N 35,000',
      quantity: 0,
      rating: 5,
      category: 'Women\'s Fashion',
      currentPrice: 35000),
];
